version: '3.8'  # Version de Docker Compose à utiliser, ici on utilise la version 3.8

services:  
  
  # Service MySQL pour la base de données principale
  mysql:
    image: mysql:8.0
    container_name: mysql-pipeline  
    restart: always  
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_pipeline  
      MYSQL_USER: user-non-root 
      MYSQL_PASSWORD: password-non-root  
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql  
    networks:
      - pipeline-network  


  # Service phpMyAdmin pour la gestion de MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-pipeline 
    restart: always 
    environment:
      PMA_HOST: mysql-pipeline 
      MYSQL_ROOT_PASSWORD: root  
    ports:
      - "8081:80"  
    networks:
      - pipeline-network  

volumes: 
  mysql_data:
    driver: local 

networks: 
  dashteam-network:
    driver: bridge  
